@echo off

:textToMorseCode
setlocal enabledelayedexpansion

set /p "string=Convert to Morse Code: "
set "output="
set "s=%string%"
:strlen_loop
if defined s (
    set "char=!s:~0,1!"
    set "s=!s:~1!"

    if /i "!char!"=="A" set "output=!output! .-" 
    if /i "!char!"=="B" set "output=!output! -..."
    if /i "!char!"=="C" set "output=!output! -.-."
    if /i "!char!"=="D" set "output=!output! -.."
    if /i "!char!"=="E" set "output=!output! ."
    if /i "!char!"=="F" set "output=!output! ..-."
    if /i "!char!"=="G" set "output=!output! --."
    if /i "!char!"=="H" set "output=!output! ...."
    if /i "!char!"=="I" set "output=!output! .."
    if /i "!char!"=="J" set "output=!output! .---"
    if /i "!char!"=="K" set "output=!output! -.-"
    if /i "!char!"=="L" set "output=!output! .-.."
    if /i "!char!"=="M" set "output=!output! --"
    if /i "!char!"=="N" set "output=!output! -."
    if /i "!char!"=="O" set "output=!output! ---"
    if /i "!char!"=="P" set "output=!output! .--."
    if /i "!char!"=="Q" set "output=!output! --.-"
    if /i "!char!"=="R" set "output=!output! .-."
    if /i "!char!"=="S" set "output=!output! ..."
    if /i "!char!"=="T" set "output=!output! -"
    if /i "!char!"=="U" set "output=!output! ..-"
    if /i "!char!"=="V" set "output=!output! ...-"
    if /i "!char!"=="W" set "output=!output! .--"
    if /i "!char!"=="X" set "output=!output! -..-"
    if /i "!char!"=="Y" set "output=!output! -.--"
    if /i "!char!"=="Z" set "output=!output! --.."
    if "!char!"=="0" set "output=!output! -----"
    if "!char!"=="1" set "output=!output! .----"
    if "!char!"=="2" set "output=!output! ..---"
    if "!char!"=="3" set "output=!output! ...--"
    if "!char!"=="4" set "output=!output! ....-"
    if "!char!"=="5" set "output=!output! ....."
    if "!char!"=="6" set "output=!output! -...."
    if "!char!"=="7" set "output=!output! --..."
    if "!char!"=="8" set "output=!output! ---.."
    if "!char!"=="9" set "output=!output! ----."
    if "!char!"=="!" set "output=!output! -.-.--"
    if "!char!"=="@" set "output=!output! .--.-."
    if "!char!"=="#" set "output=!output! .-.-.-"
    if "!char!"=="$" set "output=!output! ...-..-"
    if "!char!"=="%" set "output=!output! -..-."
    if "!char!"=="^" set "output=!output! ..--"
    if "!char!"=="&" set "output=!output! .-..."
    if "!char!"=="*" set "output=!output! -.-.-"
    if "!char!"=="(" set "output=!output! -.--."
    if "!char!"==")" set "output=!output! -.--.-"
    if "!char!"=="-" set "output=!output! -....-"
    if "!char!"=="_" set "output=!output! ..--.-"
    if "!char!"=="=" set "output=!output! -...-"
    if "!char!"=="+" set "output=!output! .-.-."
    if "!char!"=="[" set "output=!output! -.--."
    if "!char!"=="]" set "output=!output! -.--.-"
    if "!char!"=="{" set "output=!output! -.--."
    if "!char!"=="}" set "output=!output! -.--.-"
    if "!char!"=="|" set "output=!output! .-.-."
    if "!char!"=="\\" set "output=!output! -..-."
    if "!char!"==":" set "output=!output! ---..."
    if "!char!"==";" set "output=!output! -.-.-."
    if "!char!"=="'" set "output=!output! .----."
    if "!char!"=="\" set "output=!output! .-..-."
    if "!char!"=="," set "output=!output! --..--"
    if "!char!"=="." set "output=!output! .-.-.-"
    if "!char!"=="/" set "output=!output! -..-."
    goto strlen_loop
)

echo %output%
setlocal disabledelayedexpansion
goto textToMorseCode